# Generated by Django 4.0.5 on 2022-07-19 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_user_usertype_doctor_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sr_No', models.PositiveIntegerField()),
                ('Date', models.DateTimeField(max_length=100)),
                ('Time', models.CharField(max_length=100)),
                ('Helth_issue', models.TextField()),
                ('status', models.CharField(default='pending', max_length=100)),
                ('precription', models.TextField(default='not given yet')),
                ('Patient_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='myapp.user')),
                ('doctor_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctor_profile')),
            ],
        ),
    ]
