# Generated by Django 4.0.5 on 2022-07-21 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Patient_Name',
            new_name='Patient',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor_Name',
            new_name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='Sr_No',
        ),
    ]
