# Generated by Django 4.0.5 on 2022-07-21 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_appointment_precription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
